name: Publicar Homologação

on:
  push:
    branches:
      - homolog
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-homolog:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar branch homolog
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Publicar no repositório de homologação
        env:
          HOMOLOG_TOKEN: ${{ secrets.HOMOLOG_REPO_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          rm -rf .github

          git add -A
          git commit -m "prepara homologacao" || true

          git remote add homolog-pages \
            https://x-access-token:${HOMOLOG_TOKEN}@github.com/edualvesanjos/Utilitarios-Municipais-Homolog.git

          git push homolog-pages HEAD:main --force